const data = {
  products: [
    {
      _id: 1,
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      inStock: 10,
      description: "High quality product from Nike",
    },
    {
      _id: 2,
      name: "Nike polo Shirt",
      category: "T-Shirts",
      image: "/images/p1.jpg",
      price: 100,
      brand: "Nike",
      rating: 5,
      numReviews: 5,
      inStock: 8,
      description: "High quality product from Nike",
    },
    {
      _id: 3,
      name: "Addidas Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 160,
      brand: "Addidas",
      rating: 4.5,
      numReviews: 12,
      inStock: 0,
      description: "High quality product from Addidas",
    },
    {
      _id: 4,
      name: "Lacoste Free Pant",
      category: "Pants",
      image: "/images/p1.jpg",
      price: 120,
      brand: "Lacoste",
      rating: 4.5,
      numReviews: 10,
      inStock: 10,
      description: "High quality product from Lacoste",
    },
  ],
};

export default data;
